name: utc pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:

  build_job:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "helloworld"

      - name: Display README file (Windows)
        run: type README.md


  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create file
        run: touch github-action.txt

      - name: Print Hello World
        run: echo "helloworld"

      - name: Display README file (Linux)
        run: cat README.md


  deploy_job:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "helloworld"

      - name: Display README file (macOS)
        run: cat README.md
