name: utc pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: print helloworld
        run: echo "helloworld"
      - name: display readme file
        run: read README.md

  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: create file
        run: touch github-action.txt
      - name: print helloworld
        run: echo "helloworld"
      - name: display readme file
        run: cat README.md

  deploy_job:
    runs-on: macos-latest
    steps:
      - name: print helloworld
        run: echo "helloworld"
      - name: display readme file
        run: cat README.md
                